# Generated by Django 3.1.7 on 2021-05-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcompany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='reciever',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='sender',
            new_name='To',
        ),
    ]
