# Generated by Django 3.1.7 on 2021-05-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcompany', '0002_auto_20210523_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslips',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='payslips',
            name='user',
        ),
    ]
