# Generated by Django 3.1.7 on 2021-05-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itcompany', '0003_auto_20210523_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslips',
        ),
        migrations.AddField(
            model_name='emp',
            name='bank_name',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='per_annum',
            field=models.IntegerField(default=22, max_length=20),
            preserve_default=False,
        ),
    ]
