# Generated by Django 3.1.7 on 2021-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itcompany', '0004_auto_20210524_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='qualification',
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
