# Generated by Django 3.1.7 on 2021-05-26 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itcompany', '0005_auto_20210524_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('body', models.TextField()),
                ('subject', models.CharField(max_length=1000)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itcompany.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_numbers',
        ),
        migrations.AddField(
            model_name='application',
            name='experiance_in_years',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itcompany.role'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='itcompany.application'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='project_working',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='itcompany.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itcompany.employee'),
        ),
    ]
