# Generated by Django 3.1.7 on 2021-05-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itcompany', '0006_auto_20210526_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='desc',
        ),
    ]
